name: release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  REPO_SLUG: "vincent2nd/runwasi"

jobs:
  hub:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPO_SLUG }}
          ### frontend versioning
          ### on semver tag:
          # deislabs/runwasi:1.2.3
          # deislabs/runwasi:1.2
          # deislabs/runwasi:1
          # deislabs/runwasi:latest
          ### on pre-release tag:
          # deislabs/runwasi:1.1.0-rc.1
          ### on push default branch (main):
          # deislabs/runwasi:main
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=raw,value=latest
            type=ref,event=pr
          bake-target: meta-helper
          flavor: |
            latest=false
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-cross
          push: ${{ github.event_name != 'pull_request' }}

  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    needs: hub
    runs-on: ubuntu-latest
    steps:
      - name: Tar artifacts from Docker Hub
        run: |
          curl -sSf https://raw.githubusercontent.com/CaptainVincent/docker-image-extract/main/docker-image-extract | bash -s -- -p linux/arm64 -o containerd-shim-v1-linux-arm64 -- vincent2nd/runwasi
          tar czf containerd-shim-v1-${{ env.RELEASE_VERSION }}-linux-arm64.tar.gz containerd-shim-v1-linux-arm64
          curl -sSf https://raw.githubusercontent.com/CaptainVincent/docker-image-extract/main/docker-image-extract | bash -s -- -p linux/amd64 -o containerd-shim-v1-linux-amd64 -- vincent2nd/runwasi
          tar czf containerd-shim-v1-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz containerd-shim-v1-linux-amd64
      - name: upload binary to GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.gz
          file_glob: true
          overwrite: true
          prerelease: true
          tag: ${{ github.ref }}
          body: |
            Release of containerd-shim-wasmedge-v1 and containerd-shim-wasmtime-v1:${{ env.RELEASE_VERSION }} for amd64 and arm64
